//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pm04.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public int Count { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string Src { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ID_Categories { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Items_order Items_order { get; set; }
    }
}
